name: FreeBSD Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.4.1
      - name: Generate release tag
        id: tag
        run: echo "release_tag=$(wget -qO- https://api.github.com/repos/MartialBE/one-hub/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_OUTPUT
      - name: Build frontend
        env:
          CI: ""
        run: |
          cd web
          yarn install
          VITE_APP_VERSION=${{ steps.tag.outputs.release_tag }} yarn run build
          cd ..
      - name: Build binary
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 13.2
          prepare: |
            pkg install -y wget curl git gcc bash gawk gsed
            wget https://dl.google.com/go/go1.22.0.freebsd-amd64.tar.gz
            tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar.gz
            ln -s /usr/local/go/bin/go /usr/local/bin/go
          run: |
            git config --global --add safe.directory /home/runner/work/one-hub/one-hub
            cd /home/runner/work/one-hub/one-hub
            go build -ldflags "-s -w -X 'one-api/common/config.Version=${{ steps.tag.outputs.release_tag }}' -extldflags '-static'" -o one-api
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: /home/runner/work/one-hub/one-hub/one-api
